'use strict';
let feedbackOffset=0,feedbackTarget=null,feedbackGeneration=0;
const states={pending:'待处理',processing:'处理中',completed:'处理完成'};
function feedbackTime(value){return new Date(value).toLocaleString('zh-CN');}
function tab(feedback){$('dashboard').hidden=feedback;$('feedback-dashboard').hidden=!feedback;$('users-tab').setAttribute('aria-selected',String(!feedback));$('feedback-tab').setAttribute('aria-selected',String(feedback));status('');}
window.addEventListener('admin-session',e=>{feedbackGeneration++;feedbackOffset=0;feedbackTarget=null;$('feedback-detail').close();$('feedback-rows').replaceChildren();$('feedback-images').replaceChildren();$('feedback-description').textContent='';$('feedback-contact').textContent='';$('feedback-note').value='';$('feedback-filter').value='';tab(false);if(!e.detail)$('dashboard').hidden=true;});
async function loadFeedback(){const generation=feedbackGeneration;const data=await api('feedback?status='+encodeURIComponent($('feedback-filter').value)+'&offset='+feedbackOffset);if(generation!==feedbackGeneration||!csrf)return;$('feedback-rows').replaceChildren();for(const item of data.feedback){const tr=document.createElement('tr');for(const [value,cls] of [[feedbackTime(item.createdAt),''],[item.description.slice(0,90)+(item.description.length>90?'…':''),'feedback-preview'],[item.contact,'']]){const td=document.createElement('td');td.textContent=value;td.className=cls;tr.append(td);}const state=document.createElement('td'),badge=document.createElement('span');badge.className='badge '+item.status;badge.textContent=states[item.status];state.append(badge);tr.append(state);const action=document.createElement('td'),button=document.createElement('button');button.textContent='查看 / 处理';button.onclick=()=>openFeedback(item.id).catch(e=>status(e.message));action.append(button);tr.append(action);$('feedback-rows').append(tr);}if(!data.feedback.length){const tr=document.createElement('tr'),td=document.createElement('td');td.colSpan=5;td.textContent='暂无符合条件的反馈';tr.append(td);$('feedback-rows').append(tr);}$('feedback-counts').textContent=Object.entries(states).map(([key,label])=>label+' '+data.counts[key]).join(' · ');$('feedback-prev').disabled=feedbackOffset===0;$('feedback-next').disabled=!data.hasMore;}
async function openFeedback(id){const generation=feedbackGeneration,item=await api('feedback/'+encodeURIComponent(id));if(generation!==feedbackGeneration||!csrf)return;feedbackTarget=item;$('feedback-meta').textContent='编号 '+item.id+' · '+feedbackTime(item.createdAt);$('feedback-description').textContent=item.description;$('feedback-contact').textContent=item.contact;$('feedback-state').value=item.status;$('feedback-note').value=item.note;$('feedback-handler').textContent=item.handler?'最近处理：'+item.handler+' · '+feedbackTime(item.updatedAt):'尚未处理';$('feedback-save-note').textContent='';$('feedback-images').replaceChildren();for(let i=0;i<item.imageCount;i++){const link=document.createElement('a');link.href='/admin/api/feedback/'+encodeURIComponent(item.id)+'/images/'+i;link.target='_blank';link.rel='noopener';const img=document.createElement('img');img.src=link.href;img.alt='反馈图片 '+(i+1);link.append(img);$('feedback-images').append(link);}$('feedback-detail').showModal();}
$('feedback-tab').onclick=()=>{tab(true);feedbackOffset=0;loadFeedback().catch(e=>status(e.message));};$('users-tab').onclick=()=>tab(false);
$('feedback-filter').onchange=()=>{feedbackOffset=0;loadFeedback().catch(e=>status(e.message));};$('feedback-refresh').onclick=()=>loadFeedback().catch(e=>status(e.message));$('feedback-prev').onclick=()=>{feedbackOffset=Math.max(0,feedbackOffset-30);loadFeedback().catch(e=>status(e.message));};$('feedback-next').onclick=()=>{feedbackOffset+=30;loadFeedback().catch(e=>status(e.message));};$('feedback-close').onclick=()=>$('feedback-detail').close();
$('feedback-update').onsubmit=async e=>{e.preventDefault();if(!feedbackTarget)return;const button=$('feedback-save');button.disabled=true;try{await api('feedback/'+encodeURIComponent(feedbackTarget.id),{status:$('feedback-state').value,note:$('feedback-note').value,revision:feedbackTarget.revision});$('feedback-detail').close();await loadFeedback();status('反馈处理结果已保存');}catch(e){$('feedback-save-note').textContent=e.message;}finally{button.disabled=false;}};
