'use strict';
const $=id=>document.getElementById(id);let images=[],busy=false,requestId='';
function notice(text){$('notice').textContent=text;}
function previews(){const root=$('previews');root.replaceChildren();images.forEach((source,index)=>{const div=document.createElement('div');div.className='preview';const img=document.createElement('img');img.src=source;img.alt='反馈图片 '+(index+1);const button=document.createElement('button');button.type='button';button.className='remove';button.textContent='×';button.setAttribute('aria-label','删除图片 '+(index+1));button.onclick=()=>{if(busy)return;images.splice(index,1);requestId='';previews();};div.append(img,button);root.append(div);});}
async function compress(file){if(!['image/jpeg','image/png','image/webp'].includes(file.type))throw Error('请选择 JPG、PNG 或 WebP 图片');if(file.size>20*1024*1024)throw Error('单张图片不能超过 20 MB');const url=URL.createObjectURL(file);try{const img=new Image();img.src=url;await img.decode();const scale=Math.min(1,1400/Math.max(img.naturalWidth,img.naturalHeight));const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(img.naturalWidth*scale));canvas.height=Math.max(1,Math.round(img.naturalHeight*scale));const ctx=canvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(img,0,0,canvas.width,canvas.height);for(const quality of [.85,.7,.5,.3]){const value=canvas.toDataURL('image/jpeg',quality);if(value.length<=245000)return value;}throw Error('图片内容太大，请裁剪后再上传');}finally{URL.revokeObjectURL(url);}}
$('photos').onchange=async()=>{if(busy)return;const files=Array.from($('photos').files);$('photos').value='';if(images.length+files.length>3)return notice('最多上传 3 张图片，请先删除一张再添加');busy=true;$('submit').disabled=true;notice('正在处理图片…');try{const next=[];for(const file of files)next.push(await compress(file));images.push(...next);requestId='';previews();notice('');}catch(e){notice(e.message||'图片无法读取，请重新选择');}finally{busy=false;$('submit').disabled=false;}};
$('description').oninput=()=>{$('count').textContent=$('description').value.length+' / 4000';requestId='';};$('contact').oninput=()=>requestId='';
$('feedback-form').onsubmit=async e=>{e.preventDefault();if(busy)return;const description=$('description').value.trim(),contact=$('contact').value.trim();if(!description||!contact)return notice('请填写问题描述和联系方式');busy=true;$('submit').disabled=true;notice('正在提交…');try{requestId=requestId||crypto.randomUUID().replaceAll('-','');const response=await fetch('/feedback/api',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({requestId,description,contact,images,website:$('website').value})});let result;try{result=await response.json();}catch(e){throw Error('暂时无法提交，请稍后重试');}if(!response.ok)throw Error(result.detail||'提交失败，请稍后重试');$('receipt').textContent=result.feedbackId;$('form-card').hidden=true;$('success').hidden=false;notice('');images=[];requestId='';$('feedback-form').reset();previews();$('success').scrollIntoView({behavior:'smooth',block:'center'});}catch(e){notice(e.message||'网络连接失败，请稍后重试');}finally{busy=false;$('submit').disabled=false;}};
$('again').onclick=()=>{$('success').hidden=true;$('form-card').hidden=false;$('count').textContent='0 / 4000';$('description').focus();};
